Merge toolsHCK into rtoolsHCK to prevent version mismatch debuging
HCK-CI/rtoolsHCK pull request #50
Opened 2024-08-19 20:59 UTC by Jedoku

2024-08-21 09:15 UTC, akihikodaki requested changes
I don't think it is beneficial to have two levels (`shared` and `tools` for toolsHCK. I also don't know what `shared` means.

2024-08-22 10:36 UTC, Jedoku commented
> I don't think it is beneficial to have two levels (`shared` and `tools` for toolsHCK. I also don't know what `shared` means.

how about 
`extras/
  - script.ps1
  - LICENSE.script
  - README.script.md`

2024-08-22 14:37 UTC, akihikodaki commented
> > I don't think it is beneficial to have two levels (`shared` and `tools` for toolsHCK. I also don't know what `shared` means.
> 
> how about `extras/

`extras` is misleading. They are not extras, but essential part of rtoolsHCK.

> 
>     * toolsHCK.ps1
> 
>     * LICENSE.toolsHCK

`LICENSE.toolsHCK` is redundant and unnecessary.

> 
>     * README.toolsHCK.md`

2024-08-22 14:38 UTC, akihikodaki commented
`README.md` also needs to be updated as it refers to toolsHCK in a separate repository.

2024-08-26 23:10 UTC, akihikodaki requested changes

2024-08-26 23:10 UTC, akihikodaki commented on lib/rtoolsHCK.rb
> +  #                    (default: shared/tools/toolsHCK.ps1)
This needs an update.

I also suggest removing `l_script_file` option and hardcoding the path. We do not want to mix different toolsHCK and rtoolsHCK.

2024-08-28 05:38 UTC, akihikodaki requested changes

2024-08-28 05:38 UTC, akihikodaki commented on lib/rtoolsHCK.rb
> +    @l_script_file = File.expand_path('../shared/tools/toolsHCK.ps1', __dir__)
It no longer has to be kept as an instance variable of `RToolsHCK`. We can hardcode it at `Server#deploy_script_file`, which actually uses it.

2024-08-29 03:22 UTC, akihikodaki requested changes

2024-08-29 03:22 UTC, akihikodaki commented on lib/server.rb
>      end
Please remove this. We don't have to check the existence of files in general (so you don't have to check if a file exists when `require`, for example).

2024-08-29 03:22 UTC, akihikodaki commented on lib/server.rb
> +    @winrm_fs.upload(File.expand_path(tools_hck), @r_script_file)
This call of `File.expand_path` is no longer necessary.

2024-08-29 08:03 UTC, akihikodaki requested changes
One last request: remove "debuging" from the commit message. It's "debugging", and we don't need it anyway because we want to prevent "version mismatch" itself anyway.

2024-08-29 08:12 UTC, akihikodaki requested changes
I found two minor problems. They should be truely the last things remaining.

2024-08-29 08:12 UTC, akihikodaki commented on README.md
> +| :script_file | The toolsHCK.ps1 file path on local machine<br>**(default: /tools/toolsHCK.ps1)**
I missed this. This should be removed.

2024-08-29 08:12 UTC, akihikodaki commented on lib/rtoolsHCK.rb
> +
This is unrelated.

2024-08-29 08:46 UTC, akihikodaki approved these changes

2024-09-02 09:26 UTC, kostyanf14 approved these changes

2024-09-02 09:26 UTC, merged